import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      index: 'src/index.ts',
      'providers/anthropic/index': 'src/providers/anthropic/index.ts',
      'providers/openai/index': 'src/providers/openai/index.ts',
      'providers/openai-compatible/index': 'src/providers/openai-compatible/index.ts',
      'providers/deepseek/index': 'src/providers/deepseek/index.ts',
      'providers/mistral/index': 'src/providers/mistral/index.ts',
      'providers/alibaba/index': 'src/providers/alibaba/index.ts',
      'providers/azure/index': 'src/providers/azure/index.ts',
      'providers/google/index': 'src/providers/google/index.ts',
      'providers/xai/index': 'src/providers/xai/index.ts',
      'providers/groq/index': 'src/providers/groq/index.ts',
      'providers/togetherai/index': 'src/providers/togetherai/index.ts',
      'providers/huggingface/index': 'src/providers/huggingface/index.ts',
      'providers/moonshotai/index': 'src/providers/moonshotai/index.ts',
      'providers/google-vertex/index': 'src/providers/google-vertex/index.ts',
      'providers/amazon-bedrock/index': 'src/providers/amazon-bedrock/index.ts',
      'providers/perplexity/index': 'src/providers/perplexity/index.ts',
      'providers/fireworks/index': 'src/providers/fireworks/index.ts',
      'providers/cerebras/index': 'src/providers/cerebras/index.ts',
      'providers/deepinfra/index': 'src/providers/deepinfra/index.ts',
      'providers/baseten/index': 'src/providers/baseten/index.ts',
      'providers/cohere/index': 'src/providers/cohere/index.ts',
      'providers/open-responses/index': 'src/providers/open-responses/index.ts',
      // Image providers
      'providers/black-forest-labs/index': 'src/providers/black-forest-labs/index.ts',
      'providers/replicate/index': 'src/providers/replicate/index.ts',
      'providers/luma/index': 'src/providers/luma/index.ts',
      'providers/fal/index': 'src/providers/fal/index.ts',
      'providers/prodia/index': 'src/providers/prodia/index.ts',
      // Video providers
      'providers/bytedance/index': 'src/providers/bytedance/index.ts',
      'providers/klingai/index': 'src/providers/klingai/index.ts',
      // Audio providers
      'providers/elevenlabs/index': 'src/providers/elevenlabs/index.ts',
      'providers/deepgram/index': 'src/providers/deepgram/index.ts',
      'providers/assemblyai/index': 'src/providers/assemblyai/index.ts',
      'providers/revai/index': 'src/providers/revai/index.ts',
      'providers/gladia/index': 'src/providers/gladia/index.ts',
      'providers/lmnt/index': 'src/providers/lmnt/index.ts',
      'providers/hume/index': 'src/providers/hume/index.ts',
      'tools/index': 'src/tools/index.ts',
      'mcp/index': 'src/mcp/index.ts',
    },
    format: ['cjs', 'esm'],
    dts: true,
    splitting: true,
    clean: true,
    outDir: 'dist',
    external: [
      '@anthropic-ai/sdk',
      '@modelcontextprotocol/sdk',
      'openai',
      '@aws-sdk/client-bedrock-runtime',
    ],
  },
]);
